"""
The login-node half of scripts/fetch_model.sh: checks that the cluster's vLLM can
serve a model and, for a new Hugging Face repository, writes its model file.
Exits 1 if vLLM cannot serve it, 2 on any other failure.
"""
import argparse
import datetime
import json
import os
import sys

from huggingface_hub import HfApi, hf_hub_download
from huggingface_hub.utils import EntryNotFoundError

GIB = 2 ** 30
# At most this much of each 40 GB A100 goes to weights; the rest is KV cache.
# Reproduces the hand-set files: 7B -> 1 GPU, 13-14B -> 2, 32B -> 4.
WEIGHTS_PER_GPU = 20 * GIB
MEMORY = {1: ("64G", "24g"), 2: ("96G", "48g"), 4: ("128G", "64g")}

parser = argparse.ArgumentParser()
parser.add_argument("--config", help="config.json of a downloaded model, if any")
parser.add_argument("--repo", required=True)
parser.add_argument("--revision")
parser.add_argument("--name", help="with --write: the new model's name")
parser.add_argument("--write", help="model file to generate for a new repository")
args = parser.parse_args()


def fail(message):
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(2)


def fetch(filename, revision):
    try:
        return hf_hub_download(args.repo, filename, revision=revision)
    except EntryNotFoundError:
        return None


# A new model is pinned to the revision it is checked at, and downloaded at it.
info = HfApi().model_info(args.repo, revision=args.revision, files_metadata=True)
revision = args.revision or info.sha
source = args.config if args.config and os.path.isfile(args.config) else fetch("config.json", revision)
if not source:
    fail(f"{args.repo} has no config.json")
config = json.load(open(source))

#------------------------- vLLM support ----------------------------------------------

import vllm
from vllm import ModelRegistry

architectures = config.get("architectures") or []
supported = set(ModelRegistry.get_supported_archs())
print(f"vLLM {vllm.__version__}; config.json from {source}")
for a in architectures:
    print(f"  {a}: {'supported' if a in supported else 'NOT supported'}")
if not architectures:
    print("  config.json names no architecture")
if not architectures or any(a not in supported for a in architectures):
    sys.exit(1)
if not args.write:
    sys.exit(0)

#------------------------- Settings for a new model file -----------------------------

# The files fetch_model.sh downloads: safetensors, minus the duplicate formats.
weights = sum(s.size or 0 for s in info.siblings
              if s.rfilename.endswith(".safetensors")
              and not s.rfilename.startswith(("original/", "consolidated")))
# A multimodal model keeps its language model's settings in text_config.
text = config.get("text_config") or config
heads = text.get("num_attention_heads")
kv_heads = text.get("num_key_value_heads", heads)
if not weights or not heads:
    fail("no safetensors weights or no num_attention_heads; write the model file by hand")
tp = next((t for t in (1, 2, 4)
           if weights / t <= WEIGHTS_PER_GPU and heads % t == 0 and kv_heads % t == 0), None)
if tp is None:
    fail(f"{weights / GIB:.1f} GiB of weights needs more than one 4-GPU A100 node")
head_dim = text.get("head_dim") or text["hidden_size"] // heads
kv_per_token = 2 * text["num_hidden_layers"] * kv_heads * head_dim * 2   # K and V, bf16

template = ""
tokenizer_config = fetch("tokenizer_config.json", revision)
if tokenizer_config:
    t = json.load(open(tokenizer_config)).get("chat_template") or ""
    template = t if isinstance(t, str) else json.dumps(t)
jinja = fetch("chat_template.jinja", revision)
if jinja:
    template += open(jinja).read()
reasoning = "<think>" in template

memory, heap = MEMORY[tp]
with open(args.write, "w") as f:
    f.write(f"""# {args.repo}, generated by scripts/fetch_model.sh on {datetime.date.today()}.
# Review the settings below before a real run.

MODEL_DIR="{args.repo.split("/")[-1]}"
# Hugging Face repository for scripts/fetch_model.sh.
HF_REPO="{args.repo}"
HF_REVISION="{revision}"
MODEL_NAME="{args.name}"

# {weights / GIB:.1f} GiB of weights, {kv_heads} KV heads (~{kv_per_token // 1024} KB/token of KV cache):
# at most {WEIGHTS_PER_GPU // GIB} GiB of weights per 40 GB card.
TENSOR_PARALLEL={tp}
GPUS={tp}

# {"A reasoning model: its chat template opens <think>." if reasoning else "Not a reasoning model: no <think> budget needed."}
MAX_NEW_TOKENS={1024 if reasoning else 128}

# Not measured.
EXACTLEARNER_BATCH_SIZE=32

WALLTIME="${{WALLTIME:-24:00:00}}"
MEMORY="{memory}"
JAVA_HEAP="{heap}"
""")
print(f"Wrote {args.write}: TENSOR_PARALLEL={tp}, MAX_NEW_TOKENS={1024 if reasoning else 128}")
